CREATE DATABASE IF NOT EXISTS polyhacks;
USE polyhacks;
CREATE TABLE IF NOT EXISTS Confirmed (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE
);
EXIT